[Variables]
;-------------------------------------------------PATHS
SteamPath=C:\Program Files (x86)\Steam
RainMeterEXE=C:\Program Files\Rainmeter\Rainmeter.exe
GameDir = C:\Program Files (x86)\Steam
Locale = german
;-----------------------------------------------GENERAL
Mode=0
Mini=0
Fade=0
Offset=0
Header=0
Arrows=0
Search=0
HalfTiles=0
Settings=0
hiddenWindow=0
FirstGame=-5
SearchInput=Search by Name or ID
;------------------------------------------VISIBLETILES
TilePixels=225
Half=5
VisibleTiles=10.5
VisibleTilesL=10.5
VisibleTilesS=5
;---------------------------------------------FADE&SIZE
fadeMode=ON
FadeSize=#TilePixels#/2
FadeSizeL=#TilePixels#/2
FadeSizeS=30
UP=1
DOWN=1
START=0
Container=1
;------------------------------------------SKINPOSITION
SkinPosX=336
SkinPosY=168
XPLUS=0
;----------------------------------------------LOGOSIZE
LogoSize=16
LogoX=6
LogoY=2
;------------------------------------------------COLORS
Light1=61,68,80
Light2=255,255,255
Dark1=23,29,37
Dark2=0,0,0
Gray=35,37,42
Red=226,42,39
Blue=26,159,255
Opacity=255
